### ISSUE TITLE
td_wasm.cwrap() is not a function

### ISSUE THREAD

**Issue by Niek** [isopen/twasm#1]
Awesome project! I managed to compile emscripten, td, and twasm according to the instructions. Unfortunately I can't get the sample to work:
```javascript
Uncaught (in promise) TypeError: e.cwrap is not a function
```
Any idea?

**Comment by isopen** [comment]
Missing `cwrap`
Please try it https://github.com/tdlib/td/issues/18#issuecomment-435682131

**Comment by Niek** [comment]
Great, that works. This commit has the fix: https://github.com/feelfreelinux/td/commit/6dfe2970e247fafa5b2ce422efc3a6d3c6d15122
